---
# The aim of this GitHub workflow is to update the pipfile to sync with Codeflare-SDK release.
name: Sync with codeflare-sdk release
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      codeflare_sdk_release_version:
        required: true
        description: "Provide the version of the codeflare release you want to update to : "

env:
  BRANCH_NAME: main
  CODEFLARE_RELEASE_VERSION: ${{ github.event.inputs.codeflare_sdk_release_version }}
  UPDATER_BRANCH: odh-sync-updater-${{ github.run_id }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Fork repository
        id: fork
        run: | 
          REPO_NAME=abhijeet-dhumal/notebooks
          git clone --depth 1 --branch main "https://github.com/$REPO_NAME.git" Notebooks
          cd notebooks 
          git remote set-url origin "https://$GITHUB_TOKEN@github.com/$REPO_NAME.git"
          git push -u origin main
          echo "::set-output name=notebooks::$REPO_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        shell: bash

      - name: Create a new branch
        run: |
          echo ${{ env.UPDATER_BRANCH }}
          git checkout -b ${{ env.UPDATER_BRANCH }}
          git push --set-upstream origin ${{ env.UPDATER_BRANCH }}

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Update Pipfiles in accordance with Codeflare-SDK latest release
        run: |
          # list all Pipfile paths having Codeflare-SDK listed
          paths+=($(grep -rl 'codeflare-sdk = "~=.*"'))
          # Extracting only directories from file paths, excluding a `.gitworkflow` directory
          directories=()
          exclude_directories=(
            ".git/objects/pack"
            ".github/workflows/",
          )
          for path in "${paths[@]}"; do
            current_dir=$(dirname "$path")
            #Check if current_dir is not in exclude_directories list
            if [[ ! "${exclude_directories[@]}" =~ "$current_dir" ]]; then
              #Check if Pipfile exists in current_dir
              if [ -f "$current_dir/Pipfile" ];then
                directories+=("$current_dir")
              fi
            fi
          done
          # Remove duplicates
          directories=($(echo "${directories[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
          # Print the directories for verification
          echo "Directories (Start updating Pipfile in these below directories in accordance with Codeflare-SDK latest release):"
          for dir in "${directories[@]}"; do
            echo "- $dir"
          done
          # iterate over the directories and update Pipfile
          for dir in "${directories[@]}"; do
            sed -i 's/codeflare-sdk = "~=.*"/codeflare-sdk = "~='"${CODEFLARE_RELEASE_VERSION}"'"/' $dir/Pipfile
          done

      - name: Push changes
        run: |
          git fetch origin ${{ env.UPDATER_BRANCH }} && \
          git pull origin ${{ env.UPDATER_BRANCH }} && \
          git commit -am "Updated Codeflare-SDK via ${{ env.UPDATER_BRANCH }} GitHub action" && \
          git push origin ${{ env.UPDATER_BRANCH }}

      - name: Create Pull Request
        run: | 
          gh pr create --repo github.com/abhijeet-dhumal/notebooks \
          --title "CodeFlare $(BUNDLE_VERSION)" \ 
          --body ":rocket: This is an automated Pull Request. \n \n This PR updates the `Pipfile` to sync with latest Codeflare-SDK release. \n\n Created by `/.github/workflows/codeflare-sdk-release-sync.yaml` \n\n :exclamation: **IMPORTANT NOTE**: Remember to delete the ` ${{ env.UPDATER_BRANCH }}` branch after merging the changes" \
          --label "automated pr"
          --head abhijeet-dhumal:${{ env.UPDATER_BRANCH }} \
          --base main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        shell: bash

        