name: Sync with Codeflare-SDK Release
on:
  workflow_dispatch:
    inputs:
      codeflare_sdk_release_version:
        required: true
        description: "Provide the version of the Codeflare release you want to update to"
        
env:
  BRANCH_NAME: main
  CODEFLARE_RELEASE_VERSION: ${{ github.event.inputs.codeflare_sdk_release_version }}
  UPDATER_BRANCH: odh-sync-updater-${{ github.run_id }}
  REPO_OWNER: abhijeet-dhumal
  REPO_NAME: notebooks
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.BRANCH_NAME }}

      - name: Clone repository
        id: Clone
        run: |
          REPO_FULL_NAME=$REPO_OWNER/$REPO_NAME
          # Clone the forked repository
          git clone https://x-access-token:$(GITHUB_TOKEN)@github.com/abhijeet-dhumal/notebooks.git notebooks
          cd notebooks && \
          git remote add upstream "https://github.com/abhijeet-dhumal/notebooks.git" && \
          git pull upstream main && git push origin main

      - name: Update Pipfiles in accordance with Codeflare-SDK latest release
        run: |
          # list all Pipfile paths having Codeflare-SDK listed
          paths+=($(grep -rl 'codeflare-sdk = "~=.*"'))
          # Extracting only directories from file paths, excluding a `.gitworkflow` directory
          directories=()
          exclude_directories=(
            ".git/objects/pack"
            ".github/workflows/",
          )
          for path in "${paths[@]}"; do
            current_dir=$(dirname "$path")
            #Check if current_dir is not in exclude_directories list
            if [[ ! "${exclude_directories[@]}" =~ "$current_dir" ]]; then
              #Check if Pipfile exists in current_dir
              if [ -f "$current_dir/Pipfile" ];then
                directories+=("$current_dir")
              fi
            fi
          done
          # Remove duplicates
          directories=($(echo "${directories[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
          # Print the directories for verification
          echo "Directories (Start updating Pipfile in these below directories in accordance with Codeflare-SDK latest release):"
          for dir in "${directories[@]}"; do
            echo "- $dir"
          done
          # iterate over the directories and update Pipfile
          for dir in "${directories[@]}"; do
            #sed -i 's/codeflare-sdk = "~=.*"/codeflare-sdk = "~='"${CODEFLARE_RELEASE_VERSION}"'"/' $dir/Pipfile
            cd "$dir" && pipenv install codeflare-sdk~="${CODEFLARE_RELEASE_VERSION}" && pipenv --rm && cd -
          done

      - name: Push changes to forked repository
        run: |
          git add .
          git checkout -b $UPDATER_BRANCH
          git fetch origin ${{ env.UPDATER_BRANCH }} &&
          git pull origin ${{ env.UPDATER_BRANCH }} &&
          git commit -am "Updated Codeflare-SDK via ${{ env.UPDATER_BRANCH }} GitHub action" --signoff  &&
          git remote -v 
          git push origin ${{ env.UPDATER_BRANCH }}

      - name: Create Pull Request
        run: |
          gh pr create --repo $REPO_FULL_NAME \
            --title "[Digest Updater Action] Update notebook's pipfile to sync with Codeflare-SDK release version ${CODEFLARE_RELEASE_VERSION}" \
            --body ":rocket: This is an automated Pull Request. \n \n This PR updates the \`Pipfile\` to sync with the latest Codeflare-SDK release. \n\n Created by \`/.github/workflows/codeflare-sdk-release-sync.yaml\` \n\n :exclamation: **IMPORTANT NOTE**: Remember to delete the \`$UPDATER_BRANCH\` branch after merging the changes" \
            --label "automated pr" \
            --head $REPO_OWNER:${UPDATER_BRANCH} \
            --base $BRANCH_NAME 
